[CmdletBinding()]
param(
    [string] $BaseUrl
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$faultArgs = @()
if (-not [string]::IsNullOrWhiteSpace($BaseUrl)) {
    $faultArgs += @("-BaseUrl", $BaseUrl)
}

Write-Host "starting Incident 4: SetLog CPU pressure incident"
& "$PSScriptRoot/fault-cpu.ps1" @faultArgs
Write-Host "Incident 4 is active. Baseline traffic is generated by the docker compose baseline-traffic service."
Write-Host "Mitigate from another terminal after confirming render latency, backlog, and setlog CPU pressure."
