set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

printf 'starting Incident 1: SetLog DB pool latency incident\n'
sh "$SCRIPT_DIR/fault-latency.sh"
printf 'Incident 1 is active. Baseline traffic is generated by the docker compose baseline-traffic service.\n'
printf 'Mitigate from another terminal by finding SETLOG_I1_DB_POOL_HOLDER in MySQL processlist and KILLing those sessions.\n'
