set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

printf 'starting Incident 3: SetLog disk pressure incident\n'
sh "$SCRIPT_DIR/fault-disk.sh"
printf 'Incident 3 is active. Baseline traffic is generated by the docker compose baseline-traffic service.\n'
printf 'Mitigate from another terminal by removing the retained render debug log after confirming disk evidence.\n'
