[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "starting Incident 2: SetLog error increase incident"
& "$PSScriptRoot/fault-errors.ps1"
Write-Host "Incident 2 is active. Baseline traffic is generated by the docker compose baseline-traffic service."
Write-Host "Mitigate from another terminal by restoring the mysql and mysqld-exporter services."
