[CmdletBinding()]
param(
    [string] $BaseUrl
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$faultArgs = @()
if (-not [string]::IsNullOrWhiteSpace($BaseUrl)) {
    $faultArgs += @("-BaseUrl", $BaseUrl)
}

Write-Host "starting Incident 3: disk pressure drill"
& "$PSScriptRoot/fault-disk.ps1" @faultArgs
Write-Host "Incident 3 is active. Baseline traffic is generated by the docker compose baseline-traffic service."
Write-Host "Mitigate from another terminal by removing the retained render debug log after confirming disk evidence."
