set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

printf 'starting Incident 2: error increase drill\n'
sh "$SCRIPT_DIR/fault-errors.sh"
printf 'Incident 2 is active. Baseline traffic is generated by the docker compose baseline-traffic service.\n'
printf 'Mitigate from another terminal by restoring the mysql and mysqld-exporter services.\n'
