[CmdletBinding()]
param(
    [string] $BaseUrl
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$faultArgs = @()
if (-not [string]::IsNullOrWhiteSpace($BaseUrl)) {
    $faultArgs += @("-BaseUrl", $BaseUrl)
}

Write-Host "starting Incident 1: SetLog DB pool latency incident"
& "$PSScriptRoot/fault-latency.ps1" @faultArgs
Write-Host "Incident 1 is active. Baseline traffic is generated by the docker compose baseline-traffic service."
Write-Host "Mitigate from another terminal by finding SETLOG_I1_DB_POOL_HOLDER in MySQL processlist and KILLing those sessions."
