set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

printf 'starting Incident 4: CPU pressure drill\n'
sh "$SCRIPT_DIR/fault-cpu.sh"
printf 'Incident 4 is active. Baseline traffic is generated by the docker compose baseline-traffic service.\n'
printf 'Mitigate from another terminal after confirming render latency, backlog, and setlog CPU pressure.\n'
