#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BEARCLI = "/Applications/Bear.app/Contents/MacOS/bearcli"

SOURCES = {
    "lecture": {
        "id": "2A434F79-0C81-44DD-A958-A54B18A6889E",
        "title": "[복제] [멘토 특강] [유호균] SRE301: Grafana, Prometheus로 배우는 장애 모니터링 및 모의 대응 훈련",
        "outputs": [
            "LECTURE.md",
        ],
        "optional_outputs": {
            "slides": ["slides/sre301/_src/lecture-full.md"],
        },
    },
    "incident_answers": {
        "id": "FFB1B76A-0657-4BB2-94A4-A2A7647BD9BE",
        "title": "[정답] SRE301 Incident 1~4",
        "outputs": [],
        "optional_outputs": {
            "answers": ["answers/incident-drill.md"],
        },
    },
}


def fail(message: str) -> None:
    print(f"sync-bear-sources: {message}", file=sys.stderr)
    raise SystemExit(1)


def run_bearcli(bearcli: str, args: list[str]) -> str:
    try:
        completed = subprocess.run(
            [bearcli, *args],
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except FileNotFoundError:
        fail(f"bearcli not found at {bearcli}")

    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip()
        fail(f"bearcli {' '.join(args)} failed: {detail}")
    return completed.stdout


def read_note(bearcli: str, source_name: str, source: dict[str, object]) -> tuple[dict[str, object], str]:
    note_id = str(source["id"])
    expected_title = str(source["title"])

    metadata_raw = run_bearcli(bearcli, ["show", note_id, "--format", "json", "--fields", "all"])
    try:
        metadata = json.loads(metadata_raw)
    except json.JSONDecodeError as exception:
        fail(f"{source_name}: bearcli show returned invalid JSON: {exception}")

    if metadata.get("id") != note_id:
        fail(f"{source_name}: expected note id {note_id}, got {metadata.get('id')}")
    if metadata.get("title") != expected_title:
        fail(f"{source_name}: expected title {expected_title!r}, got {metadata.get('title')!r}")
    if metadata.get("locked") not in (False, "no", None):
        fail(f"{source_name}: locked Bear note cannot be used as a source")

    content_raw = run_bearcli(bearcli, ["cat", note_id, "--format", "json"])
    try:
        content_payload = json.loads(content_raw)
    except json.JSONDecodeError as exception:
        fail(f"{source_name}: bearcli cat returned invalid JSON: {exception}")

    content = content_payload.get("content")
    if not isinstance(content, str) or not content.strip():
        fail(f"{source_name}: Bear note content is empty")

    expected_length = metadata.get("length")
    actual_length = len(content.encode("utf-8"))
    if expected_length != actual_length:
        fail(
            f"{source_name}: Bear content length mismatch; metadata={expected_length}, "
            f"read={actual_length}. Refusing to accept a partial or invalid UTF-8 slice."
        )

    expected_hash = metadata.get("hash")
    if not expected_hash:
        fail(f"{source_name}: Bear metadata did not include a content hash")

    return metadata, content


def generated_markdown(source_name: str, metadata: dict[str, object], content: str, synced_at: str) -> str:
    title = str(metadata["title"])
    note_id = str(metadata["id"])
    content_hash = str(metadata["hash"])
    content_length = str(metadata["length"])
    modified = str(metadata["modified"])

    header = f"""<!--
Generated from Bear.
Source kind: {source_name}
Bear note id: {note_id}
Bear title: {title}
Bear content hash: {content_hash}
Bear content length: {content_length}
Bear modified: {modified}
Synced at: {synced_at}
Do not edit this file directly. Run `python3 scripts/sync-bear-sources.py`.
-->

"""
    return header + content.rstrip() + "\n"


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        try:
            current = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"sync-bear-sources: missing generated file {path}", file=sys.stderr)
            return False
        if current != content:
            print(f"sync-bear-sources: stale generated file {path}", file=sys.stderr)
            return False
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync SRE301 generated Markdown files from canonical Bear notes.")
    parser.add_argument("--bearcli", default=os.environ.get("BEARCLI", DEFAULT_BEARCLI))
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--include-slides", action="store_true", help="also write/check generated slides source files")
    parser.add_argument("--include-answers", action="store_true", help="also write/check generated answer files")
    parser.add_argument(
        "--synced-at",
        help="override sync timestamp for reproducible checks; defaults to current UTC time on writes",
    )
    args = parser.parse_args()

    if not Path(args.bearcli).is_file():
        fail(f"bearcli not found at {args.bearcli}")

    synced_at = args.synced_at
    if args.check:
        synced_at = None
    elif synced_at is None:
        synced_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")

    all_ok = True
    for source_name, source in SOURCES.items():
        optional_outputs = source.get("optional_outputs", {})
        outputs = list(source["outputs"])
        if args.include_slides and isinstance(optional_outputs, dict):
            outputs.extend(optional_outputs.get("slides", []))
        if args.include_answers and isinstance(optional_outputs, dict):
            outputs.extend(optional_outputs.get("answers", []))
        if not outputs:
            continue

        metadata, content = read_note(args.bearcli, source_name, source)
        if args.check:
            first_output = REPO_ROOT / str(outputs[0])
            try:
                first_content = first_output.read_text(encoding="utf-8")
            except FileNotFoundError:
                print(f"sync-bear-sources: missing generated file {first_output}", file=sys.stderr)
                all_ok = False
                continue
            marker = "Synced at: "
            synced_lines = [line for line in first_content.splitlines() if line.startswith(marker)]
            if len(synced_lines) != 1:
                print(f"sync-bear-sources: {first_output} must contain exactly one Synced at marker", file=sys.stderr)
                all_ok = False
                continue
            synced_at = synced_lines[0][len(marker) :]

        rendered = generated_markdown(source_name, metadata, content, str(synced_at))
        for output in outputs:
            if not write_or_check(REPO_ROOT / str(output), rendered, args.check):
                all_ok = False

    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
